### ISSUE TITLE
This is just a thank you

### ISSUE THREAD

**Issue by Fear113** [awesometic/realtek-r8126-dkms#2]
Thank you very much, it helped me connect the internet to my new asus rog strix x870e. I don't know what I would have done if it wasn't for you. So just thank you

**Comment by awesometic** [comment]
Hello, I'm glad to hear that. Please let me know if you have trouble with this package :)

**Comment by jay-to-the-dee** [comment]
A thank you from me as well :) This package is still the only way to get Realtek 8126 working at 2.5Gbe on Ubuntu 25.10 :)
